//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R4RClientWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class R4RClients
    {
        public int Id { get; set; }
        public int ClientID { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string country { get; set; }
    }
}
